Vagrant.configure("2") do |config|
config.vm.define "kube_master_1" do |vm1|
    vm1.vm.box = "ubuntu/jammy64"
    vm1.vm.network "private_network", ip: "192.168.56.20", name: "vboxnet0"
    vm1.vm.provider "virtualbox" do |vm1_prov|
    vm1.vm.hostname = "master1.devops"
      vm1_prov.gui = false
      vm1_prov.memory = 2048
      vm1_prov.cpus = 2
      vm1_prov.name = "kube_master_node_1"
    end 
    vm1.vm.provision "init", type: "shell", path: "master_script.sh"
  end
  config.vm.define "kube_worker_1" do |vm2|
    vm2.vm.box = "ubuntu/jammy64"
    vm2.vm.hostname = "worker1.devops"
    vm2.vm.network "private_network", ip: "192.168.56.21", name: "vboxnet0"
    vm2.vm.provider "virtualbox" do |vm2_prov|
      vm2_prov.gui = false
      vm2_prov.memory = 1024
      vm2_prov.cpus = 1
      vm2_prov.name = "kube_worker_node_1"  
    end 
    vm2.vm.provision "init", type: "shell", path: "worker_script.sh"
  end  
end

